plugins {
    id 'com.android.application'
}

android {
    namespace 'com.yallapips.keyboard'
    compileSdk 34

    defaultConfig {
        applicationId "com.yallapips.keyboard"
        minSdk 21
        targetSdk 34
        versionCode 1
        versionName "1.0.0"
    }

    signingConfigs {
        release {
            storeFile     file(System.getenv("KEYSTORE_PATH") ?: "../keystore.jks")
            storePassword System.getenv("KEYSTORE_PASS") ?: "yallapips"
            keyAlias      System.getenv("KEY_ALIAS")     ?: "yallapips"
            keyPassword   System.getenv("KEY_PASS")      ?: "yallapips"
        }
    }

    buildTypes {
        release {
            minifyEnabled false
            signingConfig signingConfigs.release
        }
        debug {
            applicationIdSuffix ".debug"
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}
